---
- include: ../provision.yml
- include: ../validate_nodes.yml
- include: ../group_by.yml tags=groupby

- include: ../prep.yml

- name: Prepare for install - RDO common
  hosts: foreman_installer:&rdo
  sudo: yes
  roles:
    - { role: product/rdo/common }
  tags:
    - prep

- name: Prepare for install - RDO - RHEL and CentOS
  hosts: foreman_installer:RedHat:CentOS:!Fedora:&rdo
  sudo: yes
  roles:
    - { role: product/rdo/rhel }
  tags:
    - prep

- name: Prepare for install - RDO - Fedora
  hosts: foreman_installer:&Fedora:&rdo
  roles:
    - { role: product/rdo/fedora }
  tags:
    - prep

- name: Prepare for Foreman install
  hosts: foreman_installer
  sudo: yes
  roles:
    - { role: foreman/common }
  tags:
    - prep

- name: Prepare foreman network
  hosts: foreman_installer:tempest
  sudo: yes
  roles:
    - { role: network-setup }
  tags:
    - prep
    - tempest_setup

- name: Prepare foreman network - Networker nodes
  hosts: networker
  sudo: yes
  roles:
    - { role: bridge-setup }
  tags:
    - prep

# apply pre-foreman workarouds
- include: ../../workarounds/workarounds-prep.yml tags=workaround

- name: Install Foreman
  hosts: foreman
  gather_facts: True
  sudo: yes
  roles:
    - { role: foreman/openstack-installer }
    - { role: foreman/hostgroup-params }
  tags:
    - install

- include: ../../workarounds/workarounds-pre-run-foreman.yml tags=workaround

- name: Install Controller node
  hosts: controller
  gather_facts: True
  sudo: yes
  roles:
    - { role: foreman/openstack-node-common }
    - { role: foreman/openstack-node }
    - { role: workarounds/glance-table-utf8,
         tags: workaround,
         when: workaround_glance_table_utf8 is defined
               and workaround_glance_table_utf8
      }
  tags:
    - install_nodes

- name: Install remaining OpenStack nodes
  hosts: foreman_node:!controller
  gather_facts: True
  sudo: yes
  roles:
    - { role: foreman/openstack-node-common }
    - { role: foreman/openstack-node }
  tags:
    - install_nodes

#- include: ../../workarounds/workarounds-post-run-foreman.yml tags=workaround

- name: Create Keystone RC files and OpenStack Status
  hosts: foreman_node
  sudo: yes
  roles:
    - { role: openstack/create-keystonerc }
  tags:
    - keystonerc

- name: Openstack status
  hosts: controller
  sudo: yes
  roles:
    - { role: openstack/openstack-status }
  tags:
    - openstack-status

- include: ../tempest.yml

- name: SELINUX error check
  hosts: all:!localhost:!tempest
  roles:
    - { role: selinux_check }
  tags:
    - provision
