--- !extends:common/common.yml
installer:
    packstack:
        config:
            CONFIG_PROVISION_DEMO: n
            CONFIG_PROVISION_TEMPEST: n
            CONFIG_SWIFT_INSTALL: n
            CONFIG_CEILOMETER_INSTALL: n
            CONFIG_HEAT_INSTALL: n
            CONFIG_HEAT_CFN_INSTALL: n
            CONFIG_HORIZON_INSTALL: n
            CONFIG_NAGIOS_INSTALL: n
            CONFIG_CINDER_INSTALL: y
