---
- include: ../provision.yml

- name: Debug list config variables
  hosts: local
  roles:
    - { role: packstack/debug }
  tags:
    - provision

- name: Prepare system for packstack
  hosts: packstack
  roles:
    - { role: common }
    - { role: linux-common }
  tags:
    - prep

# apply pre-packstack workarouds
- include: ../../workarounds/icehouse/workarounds-prep.yml tags=workaround

- name: Group hosts by product rdo/rhos
  hosts: all:!localhost:!tempest
  tasks:
    - group_by: key={{ config.product }}
  tags:
    - prep

- name: Packstack prep rhos
  hosts: controller:&rhos
  roles:
    - { role: packstack/rhos }
  tags:
    - prep

- name: Packstack prep rdo
  hosts: controller:&rdo
  roles:
    - { role: packstack/rdo }
  tags:
    - prep

- name: Group hosts by netplugin nova/neutron networking
  hosts: all:!localhost:!tempest
  tasks:
    - group_by: key={{ config.netplugin }}
  tags:
    - prep

- name: Packstack Create Answer File for neutron
  hosts: controller:&neutron
  roles:
    - { role: packstack/packstack-neutron-aio }
  tags:
    - prep

- name: Packstack Create Answer File for nova
  hosts: controller:&nova
  roles:
    - { role: packstack/packstack-nova-aio }
  tags:
    - prep

- name: Packstack Create Answer File for quantum
  hosts: controller:&quantum
  roles:
    - { role: packstack/packstack-quantum-aio }
  tags:
    - prep

- name: Ensure EPEL is off for any RHOS install
  hosts: controller:&rhos
  roles:
    - { role: packstack/rhos/epel }
  tags:
    - prep

# apply pre-packstack workarouds
- include: ../../workarounds/icehouse/workarounds-pre-run-packstack.yml tags=workaround

- name: Install packstack
  hosts: controller
  roles:
    - { role: packstack/runner }
  tags:
    - run-packstack

- name: Get Status after reboot
  hosts: controller
  roles:
    - { role: openstack/openstack-status }
  tags:
    - run-packstack

  # apply post-packstack workarouds
- include: ../../workarounds/icehouse/workarounds-post-run-packstack.yml tags=workaround-post-install

- name: Update RPMs
  hosts: packstack
  roles:
    - { role: rdopkg/update, tags: ["rdoupdate"] }

- name: List ip address of tempest node
  hosts: tempest
  user: "{{ tempest_remote_user }}"
  roles:
    - { role: tempest/iptables/node_data }
  tags:
    - tempest_setup

- name: Ensure iptables is open for tempest
  hosts: all:!localhost:!tempest
  user: "{{ remote_user }}"
  roles:
    - { role: tempest/iptables }
  tags:
    - tempest_setup

- include: ../tempest.yml