---
- include: ../dump_settings.yml

- include: ../provision.yml
- include: ../validate_nodes.yml
- include: ../group_by.yml tags=provision

- name: Debug list config variables
  sudo: no
  hosts: local
  roles:
    - { role: packstack/debug }
  tags:
    - provision

- include: ../prep.yml

# apply pre-packstack workarouds
- include: ../../workarounds/workarounds-prep.yml tags=workaround

- name: Packstack prep rhos
  hosts: controller:&rhos
  roles:
    - { role: product/rhos }
  tags:
    - prep

- name: Packstack prep rdo
  hosts: controller:&rdo
  roles:
    - { role: product/rdo }
  tags:
    - prep

- name: Group hosts by netplugin nova/neutron networking
  hosts: all:!localhost:!tempest
  tasks:
    - group_by: key=packstack-{{ config.netplugin }}
  tags:
    - prep

- name: Packstack Create Answer File for neutron
  hosts: controller:&packstack-neutron
  roles:
    - { role: packstack/packstack-neutron-aio }
  tags:
    - prep

- name: Packstack Create Answer File for nova
  hosts: controller:&packstack-nova
  roles:
    - { role: packstack/packstack-nova-aio }
  tags:
    - prep

- name: Packstack Create Answer File for quantum
  hosts: controller:&quantum
  roles:
    - { role: packstack/packstack-quantum-aio }
  tags:
    - prep

- name: Ensure EPEL is off for any RHOS install
  hosts: controller:&rhos
  roles:
    - { role: product/rhos/epel }
  tags:
    - prep

- name: Update RPMs (rdopkg)
  hosts: controller
  roles:
    - { role: rdopkg/prep, tags: ["rdoupdate-preinstall"] }
    - { role: rdopkg/preinstall, tags: ["rdoupdate-preinstall"] }

# apply pre-packstack workarouds
- include: ../../workarounds/workarounds-pre-run-packstack.yml tags=workaround

- name: Install packstack
  hosts: controller
  roles:
    - { role: packstack/runner }
  tags:
    - run-packstack

- name: Get Status after reboot
  hosts: controller
  roles:
    - { role: openstack/openstack-status }
  tags:
    - run-packstack

  # apply post-packstack workarouds
- include: ../../workarounds/workarounds-post-run-packstack.yml tags=workaround

- name: Update RPMs
  hosts: controller
  roles:
    - { role: rdopkg/prep, tags: ["rdoupdate"] }
    - { role: rdopkg/postinstall, tags: ["rdoupdate"] }

- include: tempest.yml

- name: SELINUX error check
  hosts: all:!localhost:!tempest
  roles:
    - { role: selinux_check }
  tags:
    - provision

