---
- name: Create the EPEL Repository
  template: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo
  when: ansible_distribution == "RedHat"
  notify:
    - Yum clean all

- name: Install libvirt dependencies
  yum: name={{ item }} state=latest
  with_items:
    - tftp-server
    - qemu-kvm
    - qemu-kvm-tools
    - libvirt
    - libvirt-client
    - virt-who
    - virt-what
    - fence-virtd-libvirt
    - fence-virtd-multicast
    - fence-virtd-serial
    - bpg-sans-fonts
    - virt-viewer
    - xauth
    - python-beautifulsoup4
    - rubygem-nokogiri
