---
- include: group_by.yml ansible_ssh_user=root
- include: rdo-manager-prep-host.yml

- name: Create instack user {{ instack.user.stack.name }}
  hosts: instack-virt-host
  vars:
    - ansible_ssh_user: root
  roles:
      - tripleo/instack_user

- name: setup the virt-host
  hosts: instack-virt-host
  roles:
    - rdo-manager/setup-host
    - { role: rdo-manager/gate-instack-undercloud,
        when: "\"\" != \"{{ lookup('env', 'GERRIT_PROJECT') }}\"" }
    - rdo-manager/virt-setup
    - tripleo/define-env/add-tripleo-hosts
    - { role: rdo-manager/copy-instack-undercloud-rpm,
        when: "\"\" != \"{{ lookup('env', 'GERRIT_PROJECT') }}\"" }

- name: verify ssh connection
  hosts: all:!localhost
  roles:
    - tripleo/define-env/verify-ssh

- name: Get build details
  hosts: instack-virt-host
  sudo: yes
  roles:
    - build_mark/build

- include: rdo-manager-prep-undercloud.yml

- name: install the undercloud
  hosts: undercloud
  roles:
    - rdo-manager/setup-host
    - { role: rdo-manager/install-custom-instack-undercloud-rpm,
        when: "\"\" != \"{{ lookup('env', 'GERRIT_PROJECT') }}\"" }
    - rdo-manager/install-undercloud
