---
- name: Setup of demo tenant
  keystone_user:
        tenant={{ demo_tenant_name }}
        tenant_description="{{ demo_tenant_description }}"
        login_user={{ admin_username }}
        login_password={{ admin_password }}
        login_tenant_name={{ admin_tenant_name }}
        endpoint={{ keystone_endpoint }}
        state=present

- name: Setup of demo user
  keystone_user:
        user={{ demo_username }}
        tenant={{ demo_tenant_name }}
        password={{ demo_password }}
        login_user={{ admin_username }}
        login_password={{ admin_password }}
        login_tenant_name={{ admin_tenant_name }}
        endpoint={{ keystone_endpoint }}
        state=present

- name: Apply demo role to demo user
  keystone_user:
        user={{ demo_username }}
        role={{ demo_role }}
        tenant={{ demo_tenant_name }}
        login_user={{ admin_username }}
        login_password={{ admin_password }}
        login_tenant_name={{ admin_tenant_name }}
        endpoint={{ keystone_endpoint }}
        state=present

- name: Ensure ResellerAdmin role
  keystone_user:
        user={{ admin_username }}
        role={{ swift_reseller_role }}
        tenant={{ admin_tenant_name }}
        login_user={{ admin_username }}
        login_password={{ admin_password }}
        login_tenant_name={{ admin_tenant_name }}
        endpoint={{ keystone_endpoint }}
        state=present

- name: Ensure Swift operator role
  keystone_user:
        user={{ admin_username }}
        role={{ swift_operator_role }}
        tenant={{ admin_tenant_name }}
        login_user={{ admin_username }}
        login_password={{ admin_password }}
        login_tenant_name={{ admin_tenant_name }}
        endpoint={{ keystone_endpoint }}
        state=present

- name: Create router
  quantum_router:
        name={{ router_name }}
        tenant_name={{ demo_tenant_name }}
        login_username={{ admin_username }}
        login_password={{ admin_password }}
        login_tenant_name={{ admin_tenant_name }}
        auth_url={{ keystone_endpoint }}
        state=present
  when: installer.network.plugin.name == 'neutron'

- name: Setup of private network
  quantum_network:
        name={{ private_net_name }}
        tenant_name={{ demo_tenant_name }}
        login_username={{ admin_username }}
        login_password={{ admin_password }}
        login_tenant_name={{ admin_tenant_name }}
        auth_url={{ keystone_endpoint }}
        state=present
  when: installer.network.plugin.name == 'neutron'

- name: Setup of private subnet
  quantum_subnet:
        name={{ private_subnet_name }}
        network_name={{ private_net_name }}
        cidr={{ private_subnet_cidr }}
        enable_dhcp=true
        tenant_name={{ demo_tenant_name }}
        login_username={{ admin_username }}
        login_password={{ admin_password }}
        login_tenant_name={{ admin_tenant_name }}
        auth_url={{ keystone_endpoint }}
        state=present
  when: installer.network.plugin.name == 'neutron'

- name: Add interface to router
  quantum_router_interface:
        router_name={{ router_name }}
        subnet_name={{ private_subnet_name }}
        tenant_name={{ demo_tenant_name }}
        login_username={{ admin_username }}
        login_password={{ admin_password }}
        login_tenant_name={{ admin_tenant_name }}
        auth_url={{ keystone_endpoint }}
        state=present
  when: installer.network.plugin.name == 'neutron'

- name: Setup of public network
  quantum_network:
        name={{ public_net_name }}
        router_external=yes
        tenant_name={{ public_net_tenant }}
        login_username={{ admin_username }}
        login_password={{ admin_password }}
        login_tenant_name={{ admin_tenant_name }}
        auth_url={{ keystone_endpoint }}
        state=present
  when: installer.network.plugin.name == 'neutron'

- name: Setup of public subnet
  quantum_subnet:
        name={{ public_subnet_name }}
        network_name={{ public_net_name }}
        cidr={{ tempest.public_subnet_cidr }}
        allocation_pool_start={{ tempest.public_allocation_start }}
        allocation_pool_end={{ tempest.public_allocation_end }}
        enable_dhcp=false
        tenant_name={{ public_net_tenant }}
        login_username={{ admin_username }}
        login_password={{ admin_password }}
        login_tenant_name={{ admin_tenant_name }}
        auth_url={{ keystone_endpoint }}
        state=present
  when: installer.network.plugin.name == 'neutron'

- name: Set gateway
  quantum_router_gateway:
        router_name={{ router_name }}
        network_name={{ public_net_name }}
        login_username={{ admin_username }}
        login_password={{ admin_password }}
        login_tenant_name={{ admin_tenant_name }}
        auth_url={{ keystone_endpoint }}
        state=present
  when: installer.network.plugin.name == 'neutron'

- name: Download cirros image
  get_url: url={{ cirros_image_url }} dest=~/{{ cirros_image_file }} mode=0440

#Not 100% sure what has changed in packstack juno that makes this call fail
- name: Upload cirros image to OpenStack using downloaded file
  glance_image: >
        name={{ cirros_image_name }}
        container_format={{ cirros_image_container_format }}
        disk_format={{ cirros_image_disk_format }}
        file={{ cirros_image_file }}
        is_public=yes
        login_username={{ demo_username }}
        login_password={{ demo_password }}
        login_tenant_name={{ demo_tenant_name }}
        auth_url={{ keystone_endpoint }}
        state=present
  when: product.version != 'juno'

- name: CMD Upload cirros image to OpenStack using downloaded file
  shell: source ~/keystonerc_demo; glance image-create --name=cirros-0.3.1-x86_64 --disk-format=qcow2 --container-format=bare < /home/{{nodes.tempest.remote_user}}/cirros-0.3.1-x86_64-disk.img
  sudo: yes
  when: product.version == 'juno'
