---
- name: instack-deploy-overcloud
  register: result
  ignore_errors: yes
  shell: >
      source {{ instack_user_home }}/stackrc;
      if [ -f "{{ instack_user_home }}/deploy-overcloudrc" ]; then source {{ instack_user_home }}/deploy-overcloudrc; fi;
      export CEPHSTORAGESCALE={{ nodes.cephstorage.scale | default ('1') }};
      instack-deploy-overcloud --tuskar

- name: print result of instack-deploy-overcloud install
  debug: var=result.stdout_lines
  when: result.rc == 0

- name: debug instack-deploy-overcloud failure
  when: result.rc != 0
  shell: >
      source {{ instack_user_home }}/stackrc;
      heat stack-list;
      heat resource-list overcloud;
      heat event-list overcloud;
      nova list;

- name: debug instack-deploy-overcloud failure
  when: result.rc != 0
  ignore_errors: yes
  shell: >
      source {{ instack_user_home }}/stackrc;
      heat resource-show overcloud ControllerNodesPostDeployment;

- name: grep for errors in heat-engine.log
  when: result.rc != 0
  sudo: yes
  command: "grep ERROR /var/log/heat/heat-engine.log"

- name: show ironic nodes create template
  when: result.rc != 0
  template: src=show_nodes.sh dest={{ instack_user_home }}/show_nodes.sh mode=0755

- name: show ironic nodes
  when: result.rc != 0
  shell: "{{ instack_user_home }}/show_nodes.sh"


- name: cat "/etc/edeploy"
  when: result.rc != 0
  sudo: yes
  shell: "for i in `ls /etc/edeploy/`;do echo $i; cat /etc/edeploy/$i;done"

- name: fail playbook when instack-deploy-overcloud fails
  command: echo "instack-deploy-overcloud failed, see the above debug information"
  failed_when: result.rc != 0

