---
- name: Assign provisioned host as virthost
  hosts: host0
  vars:
    - ansible_ssh_user: root
  tasks:
    - group_by: key=virthost
      when: provisioner.type in ['centosci', 'beaker', 'manual']

- include: cleanup-virthost.yml
- include: repo-{{ product.name }}.yml repo_host=virthost

- name: Create the stack user on the virthost
  hosts: virthost
  vars:
    - ansible_ssh_user: root
  tasks:
    - name: create user
      user: name="{{ provisioner.remote_user }}" state=present password=stack

    - name: copy the .bash_profile file
      command:  cp /root/.bash_profile /home/{{ provisioner.remote_user }}/

    - name: create .ssh dir
      file: path=/home/{{ provisioner.remote_user }}/.ssh mode=0700 owner=stack group=stack state=directory

    - name: copy the authorized_keys file
      command:  cp /root/.ssh/authorized_keys /home/{{ provisioner.remote_user }}/.ssh/

    - name: set file permissions on authorized_hosts
      file: path=/home/{{ provisioner.remote_user }}/.ssh/authorized_keys mode=0600 owner=stack group=stack

    - name: add user to sudoers
      lineinfile: dest=/etc/sudoers line="stack ALL=(root) NOPASSWD:ALL"

    - name: set fact for the stack user home
      set_fact: instack_user_home=/home/{{ provisioner.remote_user }}

- name: Group all hosts in gate if we are gating
  hosts: all
  tasks:
    - group_by: key=gate-instack-undercloud
      when: "\"{{ lookup('env', 'GERRIT_PROJECT') }}\" in ['instack-undercloud', 'rdo-management/instack-undercloud']"

    - group_by: key=gate-oscplugin
      when: "\"{{ lookup('env', 'GERRIT_PROJECT') }}\" in ['python-rdomanager-oscplugin', 'rdo-management/python-rdomanager-oscplugin']"

    - name: Set the gating_repo fact
      set_fact: gating_repo="python-rdomanager-oscplugin"
      when: "\"{{ lookup('env', 'GERRIT_PROJECT') }}\" in ['python-rdomanager-oscplugin', 'rdo-management/python-rdomanager-oscplugin']"

- name: Gate instack-undercloud
  hosts: virthost:&gate-instack-undercloud
  tasks:
    - name: Set the build directory as a fact
      set_fact:
        build_dir: "/tmp/{{ lookup('env', 'BUILD_TAG') }}"

    - name: Create build directory
      file: path={{ build_dir }} state=directory

    - name: Copy the instack-undercloud repo
      synchronize: src={{ lookup('env', 'PWD') }}/../instack-undercloud/ dest={{ build_dir }}/instack-undercloud delete=yes recursive=yes

    - name: remove instack-undercloud package
      yum: name=instack-undercloud state=absent
      sudo: yes

    - name: yum install packages to build rpm
      yum: name={{ item }} state=latest
      with_items:
        - git
        - python-pbr
        - python2-devel
        - rpm-build
        - rsync
      sudo: yes

    - name: Clone instack-undercloud-packaging
      command: creates={{ build_dir }}/instack-undercloud-packaging
        chdir={{ build_dir }}
        git clone https://github.com/rdo-management/instack-undercloud-packaging

    - name: add a git tag to the instack-undercloud repo
      shell: >
        chdir={{ build_dir }}/instack-undercloud
        git config user.email "rdo-ci@redhat.com";
        git config user.name "rdo-ci";
        git tag -a 999.9.9 -m "Tag for test build";

    - name: get version of package
      shell: >
        chdir={{ build_dir }}/instack-undercloud
        python setup.py --version | tail -n 1
      register: pkg_version

    - name: create the content of the package
      shell: >
        chdir={{ build_dir }}/instack-undercloud
        set +x;
        rm -rf dist/;
        python setup.py sdist;
        cd dist;
        for f in *.tar.gz; do
            cp $f {{ pkg_version.stdout }}.tar.gz;
        done;
        cd ../..;
        cp instack-undercloud-packaging/*.spec .;
        sed -i "s/^Version.*/Version: {{ pkg_version.stdout }}/" *.spec;
        sed -i "s/^Release.*/Release: 99999/" *.spec;
        rpmbuild --define "_sourcedir {{ build_dir}}/instack-undercloud/dist" --define "upstream_version {{ pkg_version.stdout }}" -bb *.spec;
        mv ~/rpmbuild/RPMS/noarch/instack-undercloud-{{ pkg_version.stdout }}-99999.noarch.rpm {{ build_dir }};

    - name: install the generated rpm
      yum: name={{ build_dir }}/instack-undercloud-{{ pkg_version.stdout }}-99999.noarch.rpm state=present
      sudo: yes

- name: Gate python-rdomanager-oscplugin
  hosts: virthost:&gate-oscplugin
  tasks:
    - name: Set the build directory as a fact
      set_fact:
        gr_build_dir: "/tmp/gr_{{ lookup('env', 'BUILD_TAG') }}"

    - name: Create build directory
      file: path={{ gr_build_dir }} state=directory

    - name: Copy the gating_repo
      synchronize: src={{ lookup('env', 'PWD') }}/../{{gating_repo}}/ dest={{ gr_build_dir }}/{{gating_repo}} delete=yes recursive=yes

    - name: remove gating_repo package
      yum: name={{ gating_repo }} state=absent
      sudo: yes

    - name: yum install packages to build rpm
      yum: name={{ item }} state=latest
      with_items:
        - git
        - python-pbr
        - python2-devel
        - rpm-build
        - rsync
      sudo: yes

    - name: Clone gating_repo packaging
      command: creates={{ gr_build_dir }}/{{ gating_repo }}-packaging
        chdir={{ gr_build_dir }}
        git clone https://github.com/rdo-management/{{ gating_repo }}-packaging

    - name: add a git tag to the gating_repo repo
      shell: >
        chdir={{ gr_build_dir }}/{{ gating_repo }}
        git config user.email "rdo-ci@redhat.com";
        git config user.name "rdo-ci";
        git tag -a 999.9.9 -m "Tag for test build";

    - name: get version of gating_repo package
      shell: >
        chdir={{ gr_build_dir }}/{{ gating_repo }}
        python setup.py --version | tail -n 1
      register: gr_pkg_version

    - name: create the content of the gating_repo package
      shell: >
        chdir={{ gr_build_dir }}/{{ gating_repo }}
        set +x;
        rm -rf dist/;
        python setup.py sdist;
        cd dist;
        for f in *.tar.gz; do
            cp $f {{ gr_pkg_version.stdout }}.tar.gz;
        done;
        cd ../..;
        cp {{ gating_repo }}-packaging/*.spec .;
        sed -i "s/^Version.*/Version: {{ gr_pkg_version.stdout }}/" *.spec;
        sed -i "s/^Release.*/Release: 99999/" *.spec;
        if [ "{{ product.repo_type is defined and product.repo_type in ['poodle', 'puddle'] }}" == "True" ]; then
            sed -i "s/tripleo-common/openstack-tripleo-common/" *.spec;
        fi;
        rpmbuild --define "_sourcedir {{ gr_build_dir}}/{{ gating_repo }}/dist" --define "upstream_version {{ gr_pkg_version.stdout }}" -bb *.spec;
        mv ~/rpmbuild/RPMS/noarch/{{ gating_repo }}-{{ gr_pkg_version.stdout }}-99999.noarch.rpm {{ gr_build_dir }};

    - name: install the generated rpm
      yum: name={{ gr_build_dir }}/{{ gating_repo }}-{{ gr_pkg_version.stdout }}-99999.noarch.rpm state=present
      sudo: yes

- name: setup the virt host
  hosts: virthost
  tasks:
    - name: set fact stack user home
      set_fact: instack_user_home=/home/{{ provisioner.remote_user }}

    - name: get the guest-image
      shell: >
        curl -o {{ instack_user_home }}/{{ distro.images[distro.name][distro.version].guest_image_name }} \
        "{{ distro.images[distro.name][distro.version].remote_file_server }}{{ distro.images[distro.name][distro.version].guest_image_name }}"

    - name: install python-rdomanager-oscplugin
      yum: name=python-rdomanager-oscplugin state=present
      sudo: yes

    - name: setup environment vars
      template: src=templates/virt-setup-env.j2 dest=~/virt-setup-env mode=0755

    - name: Contents of virt-setup-env
      shell: >
        cat {{ instack_user_home }}/virt-setup-env

    - name: run instack-virt-setup
      shell: >
        source {{ instack_user_home }}/virt-setup-env;
        instack-virt-setup;
      register: instack_virt_setup_result
      ignore_errors: yes

    - name: update libvirtd unix_sock_group
      lineinfile: dest=/etc/libvirt/libvirtd.conf
                  regexp=^unix_sock_group
                  line='unix_sock_group = "stack"'
      sudo: yes

    - name: restart libvirtd
      service: name=libvirtd state=restarted
      sudo: yes

    - name: inspect virsh capabilities
      command: 'virsh capabilities'
      sudo: yes
      when: "instack_virt_setup_result.rc != 0"
      # workaround for the SATA error RHBZ#1195882

    - name: remove libvirt qemu capabilities cache
      command: rm -Rf /var/cache/libvirt/qemu/capabilities/
      sudo: yes
      when: "instack_virt_setup_result.rc != 0"
      # more workaround for the SATA error RHBZ#1195882

    - name: restart libvirtd
      service: name=libvirtd state=restarted
      sudo: yes
      when: "instack_virt_setup_result.rc != 0"

    - name: inspect virsh capabilities
      command: 'virsh capabilities'
      when: "instack_virt_setup_result.rc != 0"

    - name: stop virbr0
      command: ip link set virbr0 down
      sudo: yes
      ignore_errors: true
      when: "instack_virt_setup_result.rc != 0"

    - name: delete libvirt bridge virbr0
      command: brctl delbr virbr0
      sudo: yes
      ignore_errors: true
      when: "instack_virt_setup_result.rc != 0"

    - name: start default libvirt network
      command: virsh net-start default
      sudo: yes
      ignore_errors: true
      when: "instack_virt_setup_result.rc != 0"

    - name: retry run instack-virt-setup
      shell: >
        virsh undefine instack;
        source {{ instack_user_home }}/virt-setup-env;
        instack-virt-setup;
      when: "instack_virt_setup_result.rc != 0"

    - name: print out all the VMs
      shell: >
        sudo virsh list --all

    - name: get undercloud vm ip address
      shell: >
        cat /var/lib/libvirt/dnsmasq/default.leases | grep $(tripleo get-vm-mac instack) | awk '{print $3;}'
      when: undercloud_ip is not defined
      register: undercloud_vm_ip_result

    - name: set_fact for undercloud ip
      set_fact: undercloud_ip={{ undercloud_vm_ip_result.stdout }}

    - name: wait until ssh is available on undercloud node
      wait_for: host={{ undercloud_ip }}
            state=started
            port=22
            delay=15
            timeout=300

    - name: add undercloud host
      add_host:
        name=undercloud
        groups=undercloud
        ansible_ssh_host=undercloud
        ansible_fqdn=undercloud
        ansible_ssh_user="{{ provisioner.remote_user }}"
        ansible_ssh_private_key_file="{{ provisioner.key_file }}"

    - name: setup ssh config
      template: src=templates/ssh_config.j2 dest=~/ssh.config.ansible mode=0755

    - name: print PWD
      debug: var=ansible_env.PWD

    - name: copy ssh_config back to the slave
      fetch: src=~/ssh.config.ansible dest=../../../ssh.config.ansible flat=yes

    - name: copy id_rsa key back to the slave
      fetch: src=~/.ssh/id_rsa dest=../../../id_rsa_virt_host flat=yes

    - name: copy undercloud root user authorized_keys to stack user
      shell: 'ssh -F ssh.config.ansible undercloud-from-virthost "cp /root/.ssh/authorized_keys /home/stack/.ssh/"'

    - name: chown authorized_keys for stack user
      shell: 'ssh -F ssh.config.ansible undercloud-from-virthost "chown stack:stack /home/stack/.ssh/authorized_keys"'

- name: regenerate the inventory file after adding hosts
  hosts: localhost
  tasks:
    - name: create inventory from template
      template:
        dest: "{{ lookup('env', 'PWD') }}/{{ tmp.node_prefix }}hosts"
        src: ../../provisioner/templates/inventory.j2

    - name: symlink inventory to a static name
      file:
        dest: "{{ lookup('env', 'PWD') }}/hosts"
        state: link
        src: "{{ lookup('env', 'PWD') }}/{{ tmp.node_prefix }}hosts"

- name: copy and install the gating rpm to the undercloud
  hosts: virthost:&gate-instack-undercloud
  tasks:
    - name: copy instack-undercloud package
      command: scp -F ssh.config.ansible {{ build_dir }}/instack-undercloud-{{ pkg_version.stdout }}-99999.noarch.rpm undercloud-from-virthost:{{ instack_user_home }}/

- name: copy and install the gating rpm to the undercloud
  hosts: virthost:&gate-oscplugin
  tasks:
    - name: copy gating_repo package
      command: scp -F ssh.config.ansible {{ gr_build_dir }}/{{ gating_repo }}-{{ gr_pkg_version.stdout }}-99999.noarch.rpm undercloud-from-virthost:{{ instack_user_home }}/

- name: test host connection
  hosts: all:!localhost
  tasks:
    - name: test ssh
      command: hostname

    - name: check distro
      command: cat /etc/redhat-release

    - name: set fact stack user home
      set_fact: instack_user_home=/home/{{ provisioner.remote_user }}

- include: repo-{{ product.name }}.yml repo_host=undercloud

- name: Group all hosts in gate if we are gating
  hosts: all
  tasks:
    - group_by: key=gate-instack-undercloud
      when: "\"{{ lookup('env', 'GERRIT_PROJECT') }}\" in ['instack-undercloud', 'rdo-management/instack-undercloud']"

    - group_by: key=gate-oscplugin
      when: "\"{{ lookup('env', 'GERRIT_PROJECT') }}\" in ['python-rdomanager-oscplugin', 'rdo-management/python-rdomanager-oscplugin']"

    - name: Set the gating_repo fact
      set_fact: gating_repo="python-rdomanager-oscplugin"
      when: "\"{{ lookup('env', 'GERRIT_PROJECT') }}\" in ['python-rdomanager-oscplugin', 'rdo-management/python-rdomanager-oscplugin']"

- name: Install the custom instack-undercloud and gating_repo rpm when gating
  hosts: undercloud:&gate-instack-undercloud
  sudo: yes
  tasks:
    - name: ensure install-undercloud is not installed
      yum: name=instack-undercloud state=absent

    - name: install the rpm we previously built
      shell: yum -y install /home/stack/instack-undercloud-*

- name: Install the custom instack-undercloud and gating_repo rpm when gating
  hosts: undercloud:&gate-oscplugin
  sudo: yes
  tasks:
    - name: ensure gating_repo is not installed
      yum: name={{ gating_repo }} state=absent

    - name: install the gating_repo rpm we previously built
      shell: yum -y install /home/stack/{{ gating_repo }}-*
