---
- name: Generate tempest_init puppet script
  template: src=tempest_init.pp.j2 dest={{ tempest.puppet_file }}

- name: Run puppet to checkout tempest and generate tempest.conf
  script: setup_tempest.sh {{ tempest.puppet_file }} {{ tempest.checkout_dir }}
  register: result

- name: Print setup_tempest.sh stdout
  debug: var=result.stdout_lines

- name: Set arbitrary things in tempest.conf
  ini_file: dest={{ tempest.checkout_dir }}/etc/tempest.conf
            section={{ item.section }}
            option={{ item.option }}
            value={{ item.value }}
  with_items:
    - { section: object-storage, option: operator_role,
        value: "{{ swift_operator_role }}" }
    - { section: identity, option: uri_v3,
        value: "http://{{ hostvars[controller_name].ansible_default_ipv4.address }}:5000/v3"}

- name: Set additional arbitrary things in tempest.conf, when required
  ini_file: dest={{ tempest.checkout_dir }}/etc/tempest.conf
            section={{ item.section }}
            option={{ item.option }}
            value={{ item.value }}
  with_items:
    - { section: identity, option: region,
        value: "{{ tempest.region }}"}
  when: tempest.region is defined

