---
- name: get the guest-image
  shell: >
    curl -o /home/stack/{{ distro.images[distro.name][ansible_distribution_version].guest_image_name }} \
    "{{ distro.images[distro.name][ansible_distribution_version].remote_file_server }}{{ distro.images[distro.name][ansible_distribution_version].guest_image_name }}"

- name: install instack-undercloud
  yum: name=instack-undercloud state=present
  sudo: yes
  when: "\"rdo-management/instack-undercloud\" != \"{{ lookup('env', 'GERRIT_PROJECT') }}\""
