---

tempest_valid_setup_methods:
    - packstack/provision
    - tempest/config_script
    - tempest/rpm

tempest_redhat_repo:
  config_script:  https://raw.githubusercontent.com/redhat-openstack/tempest/f20-patches/tools/config_tempest.py
  tempest_conf_sample: https://raw.githubusercontent.com/redhat-openstack/tempest/f20-patches/etc/tempest.conf.sample


tempest_config_image_url: http://download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-disk.img

tempest_config_generate_command: >
  python {{ tempest.dir }}/tools/config_tempest.py --out {{ tempest.dir }}/etc/tempest.conf
        --debug  --create
        identity.uri http://{{ hostvars[controller_name].ansible_default_ipv4.address }}:5000/v2.0/
        compute.allow_tenant_isolation true
        object-storage.operator_role SwiftOperator
        identity.admin_password "{{ hostvars[controller_name].admin_password | default('redhat') }}"
        identity.password "{{ hostvars[controller_name].demo_password | default('secrete') }}"
        compute.image_ref "{{ cirros_id.stdout }}"
        compute.image_ref_alt "{{ cirros_id.stdout }}"

tempest_juno_neutron_config_generate_command: >
  python {{ tempest.dir }}/tools/config_tempest.py --out {{ tempest.dir }}/etc/tempest.conf
        --debug  --create
        --network-name "public_external"
        --network-type flat
        --network-physical-label myphysnet
        --subnet-cidr "{{ tempest.public_subnet_cidr}}"
        --subnet-gateway  "{{ tempest.public_subnet_gateway }}"
        identity.uri http://{{ hostvars[controller_name].ansible_default_ipv4.address }}:5000/v2.0/
        compute.allow_tenant_isolation true
        object-storage.operator_role SwiftOperator
        identity.admin_password "{{ hostvars[controller_name].admin_password | default('redhat') }}"
        identity.password "{{ hostvars[controller_name].demo_password | default('secrete') }}"
        compute.image_ref "{{ cirros_id.stdout }}"
        compute.image_ref_alt "{{ cirros_id.stdout }}"