---
#RHEL
- name: Remove python-backports
  yum: name=python-backports state=absent

- name: Remove yum-rhn-plugin
  yum: name=yum-rhn-plugin state=absent
  register: result

- name: Yum clean all
  command: yum clean all
  when: result|changed

- name: Ensure redhat-release-server
  yum: name=redhat-release-server state=present

- name: Create the RHEL Repositories
  template: src=rhel.repo.j2 dest=/etc/yum.repos.d/rhel.repo
  notify:
    - Yum clean all
    - yum -y update to latest packages
  when: ansible_distribution_version != "7.0"

- name: Create the EPEL Repositories
  template: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo
  notify:
    - Yum clean all
  when: ansible_distribution_version != "7.0"

- name: unregister system
  command: subscription-manager unregister
  ignore_errors: yes
  when: ansible_distribution_version == "7.0"

- name: add subscription
  command: subscription-manager register --username {{ sm_username }} --password {{ sm_password }} --autosubscribe
  notify:
    - Yum clean all
    - yum -y update to latest packages
  when: ansible_distribution_version == "7.0"

- name: ensure yum-utils
  yum: name=yum-utils state=present

- name: enable rhel optional
  command: yum-config-manager --enable rhel-7-server-optional-htb-rpms
  when: ansible_distribution_version == "7.0"

#WORKAROUND
- name: Ensure /etc/sysconfig/iptables-services
  copy: src=iptables dest=/etc/sysconfig/iptables owner=root group=root mode=0600 force=no

- name: Ensure iptables
  yum: name=iptables state=present
