---
- name: reboot
  command: /sbin/shutdown -r {{ reboot_delay }} "Reboot is triggered by Ansible"

- name: Wait for host to stop
  local_action: wait_for host=${inventory_hostname} port=22 state=stopped

- name: Wait for host to come back
  local_action: wait_for host=${inventory_hostname} port=22 delay=30 timeout=600

