---
- name: yum install rdo-release for EL environment
  yum: name="{{ product.rpm[ ansible_distribution ] }}" state=present     #"
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
  retries: 3
  delay: 30
  register: rdo_release_install_result
  until: rdo_release_install_result.rc == 0

- name: check for foreman.repo file
  stat: path=/etc/yum.repos.d/foreman.repo
  register: foreman_repo_file

- name: disable foreman repo
  command: |
       sed -i -e "s/enabled=.*/enabled=0/g" /etc/yum.repos.d/foreman.repo
  when: foreman_repo_file.stat.exists

- name: disable gpgcheck for rdo for every non production repo
  lineinfile:
    dest=/etc/yum.repos.d/rdo-release.repo
    regexp=^gpgcheck=1
    line=gpgcheck=0
  when: product.repo_type != 'production'

- name: set baseurl for rdo for EL environment
  lineinfile:
    dest=/etc/yum.repos.d/rdo-release.repo
    regexp=^baseurl=
    line="baseurl={{ product.repo[product.repo_type][ansible_distribution][ansible_distribution_version] }}"
  when: product.repo_type != 'delorean'
  notify:
    - Yum clean all

- name: Create the upstream delorean repositories for Fedora RDO
  get_url: url="{{ product.repo[product.repo_type][ansible_distribution][ansible_distribution_version] }}"/delorean.repo dest=/etc/yum.repos.d/rdo-trunk-release.repo mode=0644
  notify:
    - Yum clean all
  when: product.repo_type == 'delorean'  


- name: List available yum repositories
  command: yum -d 9 repolist
  register: result

- name: Print repolist
  debug: var=result.stdout_lines
