---
- name: Create the rdo-release repositories for Fedora
  template: src=rdo.repo.j2 dest=/etc/yum.repos.d/rdo-release.repo
  notify:
    - Yum clean all

- name: disable gpgcheck for rdo for every non production repo
  lineinfile:
    dest=/etc/yum.repos.d/rdo-release.repo
    regexp=^gpgcheck=1
    line=gpgcheck=0
  when: ( "{{ config.repo }}" != 'production' )

- name: List available yum repositories
  command: yum -d 9 repolist
  register: result

- name: Print repolist
  debug: var=result.stdout_lines 

