---
- name: Set the build directory as a fact
  set_fact:
      build_dir: "/tmp/{{ lookup('env', 'BUILD_TAG') }}"

- name: Create build directory
  file: path={{ build_dir }} state=directory

- name: Copy the instack-undercloud repo
  synchronize: src=../../instack-undercloud/ dest={{ build_dir }}/instack-undercloud delete=yes recursive=yes

- name: remove instack-undercloud package
  yum: name=instack-undercloud state=absent
  sudo: yes

- name: yum install packages to build rpm
  yum: name={{ item }} state=latest
  with_items:
    - rpm-build
    - python-pbr
    - git
  sudo: yes

- name: Clone instack-undercloud-packaging
  command: creates={{ build_dir }}/instack-undercloud-packaging
      chdir={{ build_dir }}
      git clone https://github.com/rdo-management/instack-undercloud-packaging

- name: Remove the build tag if exists to get the proper version
  shell: >
      chdir={{ build_dir }}/instack-undercloud
      git tag -d {{ lookup('env', 'BUILD_TAG') }} || /bin/true

- name: get version of package
  shell: >
      chdir={{ build_dir }}/instack-undercloud
      python setup.py --version | tail -n 1
  register: pkg_version

- name: create the content of the package
  shell: >
      chdir={{ build_dir }}/instack-undercloud
      set +x;
      rm -rf dist/;
      python setup.py sdist;
      cd dist;
      for f in *.tar.gz; do
          cp $f {{ pkg_version.stdout }}.tar.gz;
      done;
      cd ../..;
      cp instack-undercloud-packaging/*.spec .;
      sed -i "s/^Version.*/Version: {{ pkg_version.stdout }}/" *.spec;
      sed -i "s/^Release.*/Release: 99999/" *.spec;
      rpmbuild --define "_sourcedir {{ build_dir}}/instack-undercloud/dist" --define "upstream_version {{ pkg_version.stdout }}" -bb *.spec;
      mv ~/rpmbuild/RPMS/noarch/instack-undercloud-{{ pkg_version.stdout }}-99999.noarch.rpm {{ build_dir }};

- name: install the generated rpm
  yum: name={{ build_dir }}/instack-undercloud-{{ pkg_version.stdout }}-99999.noarch.rpm state=present
  sudo: yes
