- name: print the test setup  command
  debug: var=test_cfg

- name: Run tests ...
  shell: >
    export PATH=$PATH:/usr/sbin;
    {{ test_cfg.run.replace('\n', '') }}
  args:
    chdir: "{{ component_path }}"
    executable: /bin/bash
  register: test_run
  ignore_errors: true

- name: print out test run
  debug: var=test_run

- name: copy test results to logs dir
  fetch: src="{{ component_path }}/{{ item }}"
         dest=../../../../logs/ flat=yes
  with_items: test_cfg.archive

- include: collect_results.yml
  when: tester.name != "pep8"

- name: pass or fail the test
  fail: msg="The test run failed"
  when: test_run.rc != 0

