---
public_net_name: public
public_subnet_name: public_sub
public_net_tenant: "{{ tempest.public_net_tenant | default('services') }}"
private_subnet_cidr: 192.168.20.0/24
private_net_name: private
private_subnet_name: private_sub
admin_username: admin
admin_tenant_name: admin
admin_password: "{{ hostvars[controller_name].admin_password | default('redhat') }}"
demo_username: demo
demo_tenant_name: demo
demo_password: "{{ hostvars[controller_name].demo_password | default('secrete') }}"
demo_role: demo
demo_tenant_description: "Demo Tenant"
router_name: router1
controller_name: "{{ nodes.controller.name }}"
keystone_endpoint: http://{{ hostvars[controller_name].ansible_default_ipv4.address }}:5000/v2.0/
cirros_image_name: cirros
cirros_image_disk_format: qcow2
cirros_image_container_format: bare
cirros_image_url: "http://download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-disk.img"
cirros_image_file: cirros-0.3.1-x86_64-disk.img
swift_operator_role: SwiftOperator
