---
- name: Acquire nodes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get nodes
      centosci:
           request="get"
           url="{{ provisioner.url }}"
           ver="{{ provisioner.distro.version }}"
           arch="{{ provisioner.arch }}"
           count="{{ provisioner.node_count }}"
      register: provisioned_nodes
      until: provisioned_nodes|success
      retries: 5
      delay: 120

    - name: Save SSID to file
      shell: >
          echo "{{ provisioned_nodes.ssid }}" > {{ lookup('env', 'PWD') }}/centosci_ssid

    - name: Add created hosts to host list
      add_host:
        name="{{ item.name }}"
        groups="provisioned"
        ansible_fqdn="{{ item.hostname }}"
        ansible_ssh_user="{{ provisioner.remote_user }}"
        ansible_ssh_private_key_file="{{ provisioner.key_file }}"
        ansible_ssh_host="{{ item.hostname }}"
      with_items: provisioned_nodes.hosts
      when: installer.type in ['rdo-manager']

    - name: Add created hosts to host list
      add_host:
        name="{{ item.name }}"
        groups="provisioned, controller, network, compute, openstack_nodes, tester"
        ansible_fqdn="{{ item.hostname }}"
        ansible_ssh_user="{{ provisioner.remote_user }}"
        ansible_ssh_private_key_file="{{ provisioner.key_file }}"
        ansible_ssh_host="{{ item.hostname }}"
      with_items: provisioned_nodes.hosts
      when: installer.type in ['packstack']

- name: wait for hosts to get reachable
  hosts: centosci
  gather_facts: no
  max_fail_percentage: 0
  tasks:
    - local_action:
        module: wait_for_ssh host={{ hostvars[inventory_hostname].ansible_ssh_host }} user=root key={{ hostvars[inventory_hostname].ansible_ssh_private_key_file }}
      sudo: no
