---
instack_user: stack
instack_user_password: $6$rounds=100000$j/3ka1xIqD.du6XZ$RX2NLJ50W9aE4FPqb3WLA7c.Djt2fFNKrfGyqVd.4aoDvrV11pri7sLluAg..WIw980ZBem/EkO/Ts4CtyERm0
root_password: $6$rounds=100000$j/3ka1xIqD.du6XZ$RX2NLJ50W9aE4FPqb3WLA7c.Djt2fFNKrfGyqVd.4aoDvrV11pri7sLluAg..WIw980ZBem/EkO/Ts4CtyERm0
instack_undercloud_pkg: instack-undercloud
