---

- name: setup virt environment for undercloud install
  hosts: instack-virt-host
  roles:
    - { role: tripleo/instack/common-undercloud }
    - { role: tripleo/instack/common }
    - { role: tripleo/instack/instack-virt-setup }
  tags: virt-setup

- name: install undercloud on vm
  hosts: instack-undercloud
  roles:
    - { role: tripleo/instack/common }
    - { role: tripleo/instack/instack-undercloud-virt}
  tags: undercloud-virt-only

- name: deploy and test overcloud
  hosts: instack-undercloud
  roles:
    - { role: tripleo/instack/common }
    - { role: tripleo/instack/deploy-overcloud }
    - { role: tripleo/instack/test-overcloud}
  tags: deploy-test-overcloud

- name: install undercloud, deploy overcloud and test on a virt system
  hosts: instack-undercloud
  roles:
    - { role: tripleo/instack/common }
    - { role: tripleo/instack/instack-undercloud-virt }
    - { role: tripleo/instack/deploy-overcloud }
    - { role: tripleo/instack/test-overcloud}
  tags: undercloud-deploy-test-virt

- name: install undercloud on baremetal
  hosts: instack-undercloud
  roles:
    - { role: tripleo/instack/common-undercloud }
    - { role: tripleo/instack/common }
    - { role: tripleo/instack/instack-undercloud-baremetal}
  tags: undercloud-baremetal-only

- name: update overcloud images
  hosts: instack
  roles:
    - { role: tripleo/instack/common }
    # - { role: tripleo/instack/update-overcloud-images }
    - { role: tripleo/instack/deploy-overcloud }
    - { role: tripleo/instack/test-overcloud}
  tags: update-overcloud-images
