---
cloud_image_base_name: "tempest"
cloud_image_base_file: "tempest.qcow2"
cloud_image_url: "http://download.fedoraproject.org/pub/fedora/linux/releases/21/Cloud/Images/x86_64/Fedora-Cloud-Base-20141203-21.x86_64.qcow2"
cloud_image_resize: "+40G"
cloud_init_iso_name: "cloud-init-iso.iso"

instance_name: "tempest"
instance_ram: "2048"
instance_vcpu: "2"

hypervisor_image_path: "/var/lib/libvirt/images/"
boot_timeout: "30"
