---
# If there is NetworkManager process running, but uninstalled, it will cause
# problems upon service network restart, searching for not-existing
# /usr/libexec/nm-dhcp-helper
- name: Ensure common dependencies
  yum: name={{ item }} state=latest
  with_items:
    - yum-utils
    - yum-plugin-priorities
    - iptables
    - libselinux-python
    - psmisc
    - redhat-lsb-core

- name: disable NetworkManager
  service: name=NetworkManager state=stopped enabled=no
  ignore_errors: yes

- name: kill all the network managers
  shell: pkill -e -9 NetworkManager
  ignore_errors: yes    # When no NM running, killall exits with 1

- name: restart the network
  service: name=network state=restarted

# cloud-init can interfere w/ openstack installs
- name: remove cloud-init
  yum: name={{ item }} state=absent
  with_items:
    - cloud-init
    - NetworkManager

- name: collect performance data, uname
  command: uname -a

- name: collect performance data, memory
  command: free -m

- name: collect performance data, vmstat
  command: vmstat

