---
- name: Run tempest
  hosts: tester
  gather_facts: no
  vars:
     skipfile: ""
  tasks:
      - name: Remove old test list
        file:
            state: absent
            name: "{{ tester.dir }}/skipfile"

      - name: Create Test List - Whitelist
        lineinfile:
            create: yes
            dest: "{{ tester.dir }}/skipfile"
            line: "+{{ item }}"
            regexp: "^[-+]{{ item }}$"
        with_items: tester.tempest.whitelist
        when: tester.tempest.whitelist

      - name: Create Test List - Blacklist
        lineinfile:
            create: yes
            dest: "{{ tester.dir }}/skipfile"
            line: "-{{ item }}"
            regexp: "^[-+]{{ item }}$"
        with_items: tester.tempest.blacklist
        when: tester.tempest.blacklist

      - name: Add skipfile invocation
        set_fact:
            skipfile: "--skip-file ./skipfile {{ tester.tempest.test_regex }}"
        when: tester.tempest.blacklist or tester.tempest.whitelist

      - name: run tempest
        shell: "{{ tester.dir }}/with_venv ./tools/run-tests.sh {{ tester.tempest.test_regex }} {{ skipfile }}"
        ignore_errors: True
        when: tester.tempest
