---
- name: Gather Logs
  hosts: all:!localhost
  gather_facts: no
  sudo: yes
  tasks:
    - name: Ensure required rpms for logging are installed
      yum: name={{ item }} state=present
      with_items:
        - gzip
        - tar

    - name: collect list of installed rpms
      shell: rpm -qa > /var/log/rpm.list

    - name: collect list of running kernel modules
      shell: lsmod > /var/log/module_list
      ignore_errors: true

    - name: prepare directory with extra logs
      file: dest=/var/log/extra state=directory
      ignore_errors: true

    - name: collect logs from all failed systemd services
      shell: |
        systemctl -t service --failed --no-legend | awk '{print $1}' \
            | xargs -r -n1 journalctl -u > /var/log/extra/services 2>&1
      ignore_errors: true

    - name: collect network status info
      shell: |
        (ip a; ip r; iptables-save) &> /var/log/extra/network;
        (for NS in $(ip netns list); do
          echo "==== $NS ====";
          ip netns exec $NS ip a;
          ip netns exec $NS ip r;
          ip netns exec $NS ip iptables-save;
          PIDS="$(ip netns pids $NS)";
          [[ ! -z "$PIDS" ]] && ps --no-headers -f --pids "$PIDS";
          echo "";
          done) &> /var/log/extra/network-netns
      ignore_errors: true
    - shell: "lsof -P &> /var/log/extra/lsof"
    - shell: "pstree -p &> /var/log/extra/pstree"
    - shell: "sysctl -a &> /var/log/extra/sysctl"
    - shell: "netstat -lnp &> /var/log/extra/netstat"
    - shell: "which openstack-status &> /dev/null && (. ~/keystonerc_admin; openstack-status &> /var/log/extra/openstack-status)"
      when: "'controller' in inventory_hostname"
      ignore_errors: true
    - shell: "lsmod &> /var/log/extra/lsmod"
    - shell: "lspci &> /var/log/extra/lspci"
    - shell: "pip list &> /var/log/extra/pip"
    - shell: "(vgs; pvs; lvs) &> /var/log/extra/lvm"
    - name: generate human-readable SAR logs
      shell: "[[ -f /usr/lib64/sa/sa2 ]] && /usr/lib64/sa/sa2 -A"
      ignore_errors: true

    - name: collect logs
      shell: |
        mkdir -p /tmp/{{ inventory_hostname }};
        for F in $(ls -d1 /var/log/rpm.list /var/log/extra {{ job.archive|join(' ') }}); do
          cp -rpL --parents $F /tmp/{{ inventory_hostname }}
        done
        cd /tmp
        tar czf {{ inventory_hostname }}.tar.gzip {{ inventory_hostname }}
      ignore_errors: true

    - name: fetch log archive (gzip)
      fetch: src=/tmp/{{ inventory_hostname }}.tar.gzip flat=yes dest=../collected_files/{{ inventory_hostname }}.tar.gzip
      ignore_errors: true



