---
- name: Group by distribution for workarounds-prep
  hosts: all:!localhost
  tasks:
    - group_by: key={{ ansible_distribution }}

- name: Group by distribution-version for workarounds-prep
  hosts: all:!localhost
  tasks:
    - group_by: key={{ ansible_distribution }}-{{ ansible_distribution_major_version|int }}

- name: Group hosts by product rdo/rhos
  hosts: all:!localhost:!tempest
  tasks:
    - group_by: key={{ product.name }}
      when: product is defined
  tags:
    - prep
