---
- name: Set selinux state
  hosts: openstack_nodes
  sudo: yes
  tasks:
    - selinux: policy=targeted state={{ distro.config.selinux|default('enforcing') }}

- name: Ensure yum presence
  hosts: openstack_nodes
  gather_facts: no
  sudo: yes
  tasks:
    - shell: python -c 'import yum' || (dnf install -y yum yum-utils && ln -snf /usr/bin/yum-deprecated /usr/bin/yum)

- name: Setup Firewall Rules
  hosts: openstack_nodes:!tester
  sudo: yes
  tasks:
    - name: Iptables - Set default rules
      command: "iptables {{ item }}"
      with_items: installer.firewall.rules

    # packstack does not change the rules if they do not conflict and
    # they are saved, so save them.
    - name: Iptables - Save default rules
      shell: /usr/sbin/iptables-save >/etc/sysconfig/iptables

- include: installer/{{ installer.type }}/main.yml

- name: Global post install
  hosts: controller
  gather_facts: yes
  tasks:
        # TODO(tkammer): move all params into khaleesi-settings
      - name: Create external network - neutron
        quantum_network:
            state: present
            auth_url: "http://{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}:35357/v2.0/"
            login_username: admin
            login_password: "{{ hostvars[inventory_hostname].admin_password | default('redhat') }}"
            login_tenant_name: admin
            name: "{{ installer.network.name }}"
            provider_network_type: flat
            provider_physical_network: "{{ installer.network.label }}"
            router_external: yes
            shared: no
            admin_state_up: yes
        when: installer is defined and installer.network.type == 'neutron'

      - name: Create subnet for external network - neutron
        quantum_subnet:
            state: present
            auth_url: "http://{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}:35357/v2.0/"
            login_username: admin
            login_password: "{{ hostvars[inventory_hostname].admin_password | default('redhat') }}"
            login_tenant_name: admin
            tenant_name: admin
            network_name: "{{ installer.network.name }}"
            name: external-subnet
            enable_dhcp: False
            gateway_ip: "{{ provisioner.network.network_list.external.subnet_gateway }}"
            cidr: "{{ provisioner.network.network_list.external.subnet_cidr}}"
            allocation_pool_start: "{{ provisioner.network.network_list.external.allocation_start }}"
            allocation_pool_end: "{{ provisioner.network.network_list.external.allocation_end }}"
        when: installer is defined and installer.network.type == 'neutron'
