---
- include: installer/{{ installer.type }}/pre.yml
- include: installer/{{ installer.type }}/run.yml
- include: installer/{{ installer.type }}/post.yml

- name: Global post install
  hosts: controller
  gather_facts: yes
  tasks:
        # TODO(tkammer): move all params into khaleesi-settings
      - name: Create external network - neutron
        quantum_network:
            state: present
            auth_url: "http://{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}:35357/v2.0/"
            login_username: admin
            login_password: "{{ hostvars[inventory_hostname].admin_password | default('redhat') }}"
            login_tenant_name: admin
            name: "{{ provisioner.network.name }}"
            provider_network_type: flat
            provider_physical_network: "{{ installer.network.label }}"
            router_external: yes
            shared: no
            admin_state_up: yes
        when: "'{{ installer.network.type }}' == 'neutron'"

      - name: Create subnet for external network - neutron
        quantum_subnet:
            state: present
            auth_url: "http://{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}:35357/v2.0/"
            login_username: admin
            login_password: "{{ hostvars[inventory_hostname].admin_password | default('redhat') }}"
            login_tenant_name: admin
            tenant_name: admin
            network_name: "{{ provisioner.network.name }}"
            name: external-subnet
            enable_dhcp: False
            gateway_ip: "{{ provisioner.network.network_list.external.subnet_gateway }}"
            cidr: "{{ provisioner.network.network_list.external.subnet_cidr}}"
            allocation_pool_start: "{{ provisioner.network.network_list.external.allocation_start }}"
            allocation_pool_end: "{{ provisioner.network.network_list.external.allocation_end }}"
        when: "'{{ installer.network.type }}' == 'neutron'"
