---
# provison
- include: dump_settings.yml
- include: provision.yml
- include: group_by.yml tags=provision

# prep
- include: packstack/setup-ssh-keys.yml tags=prep
- include: prep.yml

- name: Prepare network for Packstack install
  sudo: yes
  hosts:
    - controller
    - compute
    - tempest
  tags: provision
  roles:
    -  network-setup

- include: validate_nodes.yml

- name: Debug list config variables
  hosts: local
  sudo: no
  tags: provision
  roles:
    - { role: packstack/debug }


# apply pre-packstack workarouds
- include: ../workarounds/workarounds-prep.yml tags=workaround

- name: Setup packstack on Controller (rdo)
  hosts: controller:&rdo
  sudo: yes
  roles:
      - product/rdo
  tags: prep

- name: Setup packstack on Controller (rhos)
  hosts: controller:&rhos
  sudo: yes
  roles:
      - product/rhos
  tags: prep

- name: Prepare  network bridge
  hosts: controller
  sudo: yes
  roles:
    - { role: bridge-setup }
  tags:
    - prep

# Generate answers
- name: Setup packstack on Controller
  hosts: controller
  sudo: yes
  roles:
      - packstack/generate-answers
  tags: prep

- include: ../workarounds/workarounds-pre-run-packstack.yml tags=workaround

# packstack_run

- name: Run packstack
  hosts: controller
  sudo: yes
  roles:
    - { role: packstack/runner }
  tags: packstack_run

- include: ../workarounds/workarounds-post-run-packstack.yml tags=workaround

- name: Get Status after reboot
  hosts: controller
  sudo: yes
  tags: packstack-run
  roles:
    - { role: openstack/openstack-status }

# sahara
- include: sahara.yml

# tempest
- name: List ip address of tempest node
  hosts: tempest
  sudo: yes
  roles:
    - { role: tempest/iptables/node_data }
  tags: tempest_setup

- name: Ensure iptables is open for tempest
  hosts: all:!localhost:!tempest
  sudo: yes
  roles:
    - { role: tempest/iptables }
  tags: tempest_setup

- include: tempest.yml

- name: SELINUX error check
  hosts: all:!localhost:!tempest
  sudo: yes
  roles:
    - { role: selinux_check }
  tags: provision

- name: RHOS SELINUX error check
  hosts: all:!localhost:!tempest:&rhos
  sudo: yes
  roles:
    - { role: selinux_check/rhos }
  tags: provision

