---
- name: Gather facts from controller and compute
  hosts: all:!localhost:!tempest
  sudo: yes
  tags:
    - tempest_setup
    - tempest_run

- name: tempest | Workaround | config_tempest.py | create openstack resources
  hosts: controller
  sudo: yes
  tags:
    - workaround
    - workaround-tempest-config-tool
  vars:
      apply_patch: workaround_config_tempest_tool|default(false)
  tasks:
      - script: ../workarounds/tempest/setup_openstack_env.sh
        when: apply_patch


- name: Create keystonerc
  hosts: tempest:!skip_tempest_setup
  sudo: yes
  tags: tempest_setup
  roles:
    - { role: openstack/create-keystonerc }

- name: Update RPMs on tempest node
  hosts: tempest:!skip_rdoupdate_tempest
  sudo: yes
  roles:
    - { role: rdopkg/prep, when: rdopkg.update is defined, tags: ["rdoupdate_tempest"] }

- name: Setup tempest and install packages for tempest
  hosts: tempest:!skip_tempest_setup
  tags: tempest_setup
  roles:
    - { role: tempest/package-dependencies, sudo: yes }
    - { role: tempest/setup-openstack-elements, when: product.version == "havana" or product.version == "4.0"}
    - { role: tempest/download-cirros, sudo: yes }
    - { role: tempest/setup }
    - { role: tempest/security-groups, sudo: yes }


- name: Run tempest
  hosts: tempest
  tags: tempest_run
  roles:
    - { role: tempest/run }

